import type { Question } from "../domain/types";

type Activity = {
  text?: string;
  prompt: string;
  choices: [string, string, string];
};
export type VocabularyWord = {
  id: string;
  word: string;
  forms: string[];
  meaning: string;
  example: string;
  activities: Activity[];
};
// The first choice is the answer in the authored bank; session creation shuffles it.
// Each sense has its own ID. These are study candidates, not grade-level norms.
const activity = (
  prompt: string,
  correct: string,
  wrong1: string,
  wrong2: string,
  text?: string,
): Activity => ({ prompt, choices: [correct, wrong1, wrong2], text });
const word = (
  id: string,
  name: string,
  forms: string[],
  meaning: string,
  example: string,
  wrong: [string, string],
  practice: Activity,
  readingA: Activity,
  readingB: Activity,
): VocabularyWord => ({
  id,
  word: name,
  forms: [name, ...forms],
  meaning,
  example,
  activities: [
    activity(`¿Qué significa «${name}»?`, meaning, ...wrong),
    practice,
    readingA,
    readingB,
  ],
});

export const vocabulary: VocabularyWord[] = [
  word(
    "identificar",
    "identificar",
    ["identifica", "identificas"],
    "Reconocer cuál es la persona, cosa o idea que buscas.",
    "Si buscas tu mochila entre varias y reconoces la tuya, la puedes identificar.",
    ["Cambiar una cosa por otra.", "Inventar algo que no existe."],
    activity(
      "Te piden identificar al personaje que cuenta la historia. ¿Qué haces?",
      "Busco quién cuenta lo que pasó.",
      "Cambio el final.",
      "Cuento las páginas.",
    ),
    activity(
      "¿Qué pista permite identificar el cuaderno de Inés?",
      "Tiene una estrella en la portada.",
      "Está en una mesa.",
      "Tiene hojas.",
      "Hay tres cuadernos sobre la mesa. Todos tienen hojas blancas. Solo el de Inés tiene una estrella en la portada.",
    ),
    activity(
      "¿A quién puedes identificar como la persona que trajo la pelota?",
      "A Tomás.",
      "A Eva.",
      "A Leo.",
      "Eva llegó con agua. Tomás sacó una pelota de su mochila. Leo llevó los vasos.",
    ),
  ),
  word(
    "senalar",
    "señalar",
    ["señala", "señalas"],
    "Mostrar o indicar algo para que otra persona lo encuentre.",
    "Puedes señalar en el mapa el lugar donde vives.",
    ["Esconder algo para que nadie lo vea.", "Contar una historia completa."],
    activity(
      "La maestra dice: «Señala el título». ¿Qué haces?",
      "Indico dónde está el título.",
      "Borro el título.",
      "Escribo otro cuento.",
    ),
    activity(
      "Si debes señalar la frase que dice dónde está el gato, ¿cuál eliges?",
      "El gato duerme debajo de la silla.",
      "El gato se llama Sol.",
      "El gato tiene hambre.",
      "El gato se llama Sol. El gato duerme debajo de la silla. El gato tiene hambre.",
    ),
    activity(
      "¿Qué debes señalar para mostrar a qué hora empieza la función?",
      "A las cinco.",
      "En el patio.",
      "Una obra de teatro.",
      "El cartel anuncia una obra de teatro. Será en el patio y empezará a las cinco.",
    ),
  ),
  word(
    "comparar",
    "comparar",
    ["compara", "comparas"],
    "Buscar en qué se parecen y en qué son diferentes dos o más cosas.",
    "Al comparar una bicicleta y un patín, puedes mirar sus ruedas y su tamaño.",
    [
      "Elegir algo sin mirar las demás opciones.",
      "Decir lo mismo muchas veces.",
    ],
    activity(
      "¿Quién está comparando dos cuentos?",
      "Ana dice qué tienen en común y qué cambia.",
      "Luis guarda los libros.",
      "Pablo lee solo un título.",
    ),
    activity(
      "Al comparar las mochilas, ¿qué puedes decir?",
      "Las dos tienen bolsillos, pero son de distinto color.",
      "Las dos son rojas.",
      "Ninguna tiene bolsillos.",
      "La mochila de Luz es roja y tiene dos bolsillos. La de Max es azul y también tiene dos bolsillos.",
    ),
    activity(
      "¿Qué frase compara a los dos personajes?",
      "Ambos ayudan, pero de distintas maneras.",
      "Clara tiene una planta.",
      "Bruno mira el jardín.",
      "Clara riega las plantas del salón. Bruno recoge las hojas secas. Los dos ayudan a cuidar el jardín.",
    ),
  ),
  word(
    "explicar",
    "explicar",
    ["explica", "explicas"],
    "Contar cómo es, cómo se hace o por qué pasa algo para que se entienda.",
    "Puedes explicar un juego contando sus reglas paso a paso.",
    ["Repetir una palabra sin decir nada más.", "Ocultar cómo se hace algo."],
    activity(
      "¿Qué respuesta explica por qué llegaste tarde?",
      "Llegué tarde porque el autobús se descompuso.",
      "Tarde, tarde, tarde.",
      "Me gusta el autobús.",
    ),
    activity(
      "¿Qué frase explica cómo cuidar la planta?",
      "Ponla cerca de la luz y riega cuando la tierra esté seca.",
      "La planta es bonita.",
      "La maceta es verde.",
      "Dani quiere cuidar su planta. Su abuela le dice: «Ponla cerca de la luz y riega cuando la tierra esté seca».",
    ),
    activity(
      "¿Qué explica la nota de Laura?",
      "Por qué el equipo jugará dentro del salón.",
      "De qué color es el balón.",
      "Quién ganó el partido de ayer.",
      "Laura escribió: «Hoy jugaremos dentro del salón porque está lloviendo y el patio está resbaloso».",
    ),
  ),
  word(
    "secuencia",
    "secuencia",
    ["secuencias"],
    "Una serie de pasos o hechos que van en un orden.",
    "Lavarte las manos, comer y lavar tu plato forman una secuencia.",
    [
      "Un grupo de hechos que no tienen ningún orden.",
      "El nombre de quien escribe un libro.",
    ],
    activity(
      "¿Qué secuencia sirve para preparar un sándwich?",
      "Poner el relleno, cerrar el pan y comer.",
      "Comer, poner el relleno y cerrar el pan.",
      "Cerrar el pan, comer y poner el relleno.",
    ),
    activity(
      "¿Cuál es la secuencia de lo que hizo Omar?",
      "Buscó semillas, las sembró y las regó.",
      "Regó, buscó semillas y las sembró.",
      "Sembró, regó y buscó semillas.",
      "Omar buscó unas semillas. Después las puso en una maceta. Al final les echó agua.",
    ),
    activity(
      "En esta secuencia, ¿qué ocurrió después de amasar?",
      "Cortaron las galletas.",
      "Mezclaron los ingredientes.",
      "Guardaron las galletas.",
      "Primero mezclaron los ingredientes. Luego amasaron. Después cortaron las galletas y, al final, las hornearon.",
    ),
  ),
  word(
    "anteriormente",
    "anteriormente",
    [],
    "Antes del momento del que estamos hablando.",
    "Ahora vivo aquí; anteriormente vivía en otra calle.",
    ["Después del momento del que hablamos.", "Exactamente al mismo tiempo."],
    activity(
      "«Ahora el patio tiene árboles. Anteriormente no tenía». ¿Cómo era antes?",
      "No tenía árboles.",
      "Tenía más árboles.",
      "Era igual que ahora.",
    ),
    activity(
      "¿Qué hacía Sara anteriormente?",
      "Leía con ayuda.",
      "Leía sola todos los días.",
      "Escribía un libro.",
      "Ahora Sara lee sola un cuento cada noche. Anteriormente, su hermano la ayudaba a leer las frases largas.",
    ),
    activity(
      "¿Para qué servía el cuarto anteriormente?",
      "Para guardar cajas.",
      "Para leer.",
      "Para cocinar.",
      "Ahora usamos este cuarto para leer. Anteriormente guardábamos cajas aquí.",
    ),
  ),
  word(
    "posteriormente",
    "posteriormente",
    [],
    "Después del momento del que estamos hablando.",
    "Primero hicimos la tarea; posteriormente salimos a jugar.",
    ["Antes de lo que estamos contando.", "En un lugar muy lejano."],
    activity(
      "«Compramos las semillas y posteriormente las sembramos». ¿Qué pasó después?",
      "Sembramos las semillas.",
      "Compramos las semillas.",
      "Las dos cosas pasaron al mismo tiempo.",
    ),
    activity(
      "¿Qué hicieron posteriormente?",
      "Escribieron sobre lo que vieron.",
      "Visitaron el museo.",
      "Compraron un museo.",
      "El grupo visitó un museo. Posteriormente, ya en la escuela, cada niña escribió sobre lo que vio.",
    ),
    activity(
      "¿Qué hará Noé posteriormente?",
      "Pintará la figura.",
      "Hará la figura de barro.",
      "Buscará otro material.",
      "Noé hizo una figura de barro. Esperará a que se seque y posteriormente la pintará.",
    ),
  ),
  word(
    "causa",
    "causa",
    ["causas"],
    "La razón por la que pasa algo.",
    "El patio se mojó porque llovió. La lluvia fue la causa.",
    [
      "Lo que pasa como resultado de otra cosa.",
      "El lugar donde termina un cuento.",
    ],
    activity(
      "El vaso se cayó porque alguien empujó la mesa. ¿Cuál fue la causa?",
      "Alguien empujó la mesa.",
      "El vaso quedó en el suelo.",
      "El vaso era transparente.",
    ),
    activity(
      "¿Cuál fue la causa de que la ropa se mojara?",
      "Empezó a llover.",
      "La ropa estaba limpia.",
      "El sol salió.",
      "La ropa estaba tendida en el patio. Empezó a llover y la ropa se mojó.",
    ),
    activity(
      "¿Cuál fue la causa de que Eva llegara a tiempo?",
      "Salió de casa más temprano.",
      "La escuela cerró.",
      "Se olvidó de su mochila.",
      "Eva sabía que el camino era largo. Salió de casa más temprano y así llegó a tiempo a la escuela.",
    ),
  ),
  word(
    "consecuencia",
    "consecuencia",
    ["consecuencias"],
    "Lo que sucede como resultado de algo que pasó antes.",
    "Llovió y el patio se mojó. Que el patio se mojara fue la consecuencia.",
    ["La razón que hace que algo pase.", "El nombre de un personaje."],
    activity(
      "Nadie regó la planta y se secó. ¿Cuál fue la consecuencia?",
      "La planta se secó.",
      "Nadie la regó.",
      "La planta tenía una maceta.",
    ),
    activity(
      "¿Qué consecuencia tuvo reparar la bicicleta?",
      "Luis pudo volver a usarla.",
      "La llanta estaba rota.",
      "Luis perdió la bicicleta.",
      "La bicicleta de Luis tenía una llanta rota. Su tía la reparó. Gracias a eso, Luis pudo volver a usarla.",
    ),
    activity(
      "¿Cuál fue la consecuencia de ordenar los libros?",
      "Fue más fácil encontrarlos.",
      "Había libros por todas partes.",
      "Desaparecieron los cuentos.",
      "Había libros por todas partes. El grupo los ordenó por tema. Desde entonces fue más fácil encontrarlos.",
    ),
  ),
  word(
    "parrafo",
    "párrafo",
    ["párrafos"],
    "Un grupo de oraciones que hablan de una misma idea y termina con punto y aparte.",
    "Puedes escribir un párrafo sobre tu perro y otro sobre cómo lo cuidas.",
    ["Una sola letra del abecedario.", "El nombre que aparece en la portada."],
    activity(
      "¿Cuándo conviene empezar otro párrafo?",
      "Cuando empiezas a hablar de otra idea.",
      "Después de cada letra.",
      "Solo cuando se acaba todo el cuaderno.",
    ),
    activity(
      "¿De qué habla el segundo párrafo?",
      "De cómo cuidan a Miel.",
      "Del color de Miel.",
      "De un gato nuevo.",
      "Miel es una perrita pequeña. Tiene el pelo café y las orejas largas.\n\nCada mañana le damos agua y comida. Por la tarde salimos a pasear con ella.",
    ),
    activity(
      "¿Por qué el texto tiene dos párrafos?",
      "Uno describe el huerto y otro cuenta lo que harán allí.",
      "Cada párrafo tiene una sola letra.",
      "Los dos hablan de cosas que no tienen relación.",
      "El huerto está junto al salón. Tiene tres macetas grandes.\n\nMañana sembraremos rábanos. Después pondremos letreros para recordar dónde están.",
    ),
  ),
  word(
    "idea-principal",
    "idea principal",
    ["ideas principales"],
    "Lo más importante que nos cuenta un texto.",
    "Si el texto explica cómo cuidar un perro, esa es su idea principal.",
    [
      "Cualquier palabra que aparezca al final.",
      "Un dato pequeño que puede quitarse sin cambiar el tema.",
    ],
    activity(
      "Un texto explica cómo ahorrar agua en casa. ¿Cuál sería su idea principal?",
      "Podemos cuidar el agua con acciones de todos los días.",
      "La llave del baño es plateada.",
      "El jabón huele a limón.",
    ),
    activity(
      "¿Cuál es la idea principal?",
      "El grupo trabajó junto para limpiar el patio.",
      "El patio tenía una banca azul.",
      "Solo una persona hizo todo.",
      "El grupo limpió el patio. Unos recogieron papeles; otros barrieron. Al trabajar juntos, terminaron pronto.",
    ),
    activity(
      "¿Cuál es la idea principal?",
      "La biblioteca ofrece varias formas de disfrutar los libros.",
      "Todos los libros tienen la misma portada.",
      "La biblioteca solo presta lápices.",
      "En la biblioteca puedes llevar libros a casa. También hay lecturas en voz alta y un rincón para leer con amigos.",
    ),
  ),
  word(
    "detalle",
    "detalle",
    ["detalles"],
    "Un dato pequeño que ayuda a describir o entender algo mejor.",
    "Decir que una mochila tiene un bolsillo rojo añade un detalle.",
    [
      "Todo el tema de una lectura en una frase.",
      "Una historia que siempre es falsa.",
    ],
    activity(
      "«La niña llevaba botas amarillas». ¿Qué detalle describe las botas?",
      "Eran amarillas.",
      "La niña caminaba.",
      "Había una niña.",
    ),
    activity(
      "¿Qué detalle ayuda a imaginar el sombrero?",
      "Tenía una cinta verde.",
      "La tía llegó.",
      "Era por la mañana.",
      "Mi tía llegó por la mañana. Llevaba un sombrero con una cinta verde y dejó su bolso en la mesa.",
    ),
    activity(
      "¿Qué detalle nos dice cómo era la caja?",
      "Era pequeña y tenía puntos azules.",
      "Mara la abrió.",
      "Había una caja.",
      "Mara recibió una caja pequeña con puntos azules. Al abrirla, encontró una carta de su prima.",
    ),
  ),
  word(
    "fabula",
    "fábula",
    ["fábulas"],
    "Una historia corta que deja una enseñanza; muchas tienen animales que hablan.",
    "Una historia de dos hormigas que aprenden a ayudarse puede ser una fábula.",
    ["Una lista de compras.", "Una noticia que cuenta un hecho real de hoy."],
    activity(
      "¿Cuál podría ser una fábula?",
      "Un zorro y un ratón hablan y aprenden a compartir.",
      "Una receta con sus ingredientes.",
      "El horario de los autobuses.",
    ),
    activity(
      "¿Qué hace que esta historia sea una fábula?",
      "Los animales actúan como personas y la historia deja una enseñanza.",
      "Explica cómo construir un nido paso a paso.",
      "Cuenta una noticia real.",
      "Una ardilla no quiso compartir sus nueces. Cuando necesitó ayuda, nadie se acercó. Entonces aprendió que también debía ayudar a los demás.",
    ),
    activity(
      "¿Qué enseñanza podría dejar esta fábula?",
      "Pedir ayuda puede servir para resolver un problema.",
      "Es mejor esconder todos los problemas.",
      "Nunca debemos hablar con nuestros amigos.",
      "Un conejo intentó mover una rama él solo. Le dijo a una tortuga: «¿Me ayudas?». Juntos lograron apartarla del camino.",
    ),
  ),
  word(
    "moraleja",
    "moraleja",
    ["moralejas"],
    "La enseñanza que nos deja una historia.",
    "Una historia puede tener como moraleja que es mejor decir la verdad.",
    [
      "El nombre de quien escribió la historia.",
      "El lugar donde empieza la aventura.",
    ],
    activity(
      "¿Qué frase puede ser una moraleja?",
      "Con ayuda podemos resolver mejor algunos problemas.",
      "El bosque tenía diez árboles.",
      "El ratón se llamaba Tito.",
    ),
    activity(
      "¿Cuál sería la moraleja?",
      "Compartir ayuda a que todos podamos disfrutar.",
      "Es mejor guardar todo para uno mismo.",
      "Las manzanas crecen en el mar.",
      "Un oso guardó todas las manzanas y comió solo. Al día siguiente compartió con sus amigos y disfrutó mucho más la merienda.",
    ),
    activity(
      "¿Qué moraleja deja la historia?",
      "Escuchar a otros puede ayudarnos a aprender.",
      "Solo debemos escuchar nuestra propia voz.",
      "Nunca vale la pena intentar algo nuevo.",
      "Un búho joven creía saberlo todo. No escuchó cómo hacer un nido y el suyo se cayó. Pidió consejo y construyó uno más firme.",
    ),
  ),
  word(
    "refran",
    "refrán",
    ["refranes"],
    "Una frase conocida que da un consejo o una enseñanza.",
    "«No dejes para mañana lo que puedes hacer hoy» aconseja hacer las cosas a tiempo.",
    [
      "Una lista de los personajes de un cuento.",
      "Una palabra que nombra un color.",
    ],
    activity(
      "¿Qué consejo da el refrán «Más vale prevenir que lamentar»?",
      "Es mejor cuidarnos antes de que ocurra un problema.",
      "Siempre debemos preocuparnos por todo.",
      "Conviene esperar a que algo salga mal.",
    ),
    activity(
      "¿Por qué la abuela usa este refrán?",
      "Para aconsejar a Leo que no deje su tarea para después.",
      "Para decir que mañana no habrá clases.",
      "Para pedirle que tire su tarea.",
      "Leo quiere dejar su tarea para mañana. Su abuela dice: «No dejes para mañana lo que puedes hacer hoy».",
    ),
    activity(
      "¿Qué aconseja aquí el refrán «La práctica hace al maestro»?",
      "Seguir practicando para mejorar.",
      "Dejar el dibujo para siempre.",
      "Dibujar solo si ya sale perfecto.",
      "A Nina todavía no le sale bien su dibujo. Su papá le recuerda: «La práctica hace al maestro». Nina decide intentarlo otra vez.",
    ),
  ),
  word(
    "relato-historico",
    "relato histórico",
    ["relatos históricos"],
    "Un texto que cuenta hechos reales del pasado.",
    "La historia de cuándo se fundó tu escuela puede ser un relato histórico.",
    [
      "Un cuento de magia que alguien inventó.",
      "Una lista de deseos para el futuro.",
    ],
    activity(
      "¿Qué usarías para escribir un relato histórico de tu escuela?",
      "Documentos y fotos que ayuden a saber qué pasó.",
      "Solo lo que imagino que pudo pasar.",
      "Una receta de cocina.",
    ),
    activity(
      "¿Qué ayuda a que este texto sea un relato histórico?",
      "Cuenta hechos pasados y los comprueba con documentos.",
      "Inventa personajes con poderes mágicos.",
      "Solo dice lo que quieren hacer el próximo año.",
      "Para contar cómo nació la biblioteca, el grupo revisó su acta de apertura y fotos antiguas. Con esas fuentes escribió lo que ocurrió, en el orden en que pasó.",
    ),
    activity(
      "¿Qué parte podría formar parte de un relato histórico del pueblo?",
      "Lo que pasó cuando se construyó el puente, comprobado con fotos y documentos.",
      "Una aventura inventada sobre un dragón en el puente.",
      "Un deseo de construir un castillo en el futuro.",
      "La clase prepara un libro sobre el pasado del pueblo. Buscará información sobre cuándo y cómo se construyó su puente.",
    ),
  ),
  word(
    "deducir",
    "deducir",
    ["deduce", "deduces"],
    "Entender algo usando pistas, aunque no esté dicho directamente.",
    "Si ves un paraguas mojado, puedes deducir que quizá llovió.",
    [
      "Copiar exactamente una frase del texto.",
      "Elegir una respuesta sin mirar ninguna pista.",
    ],
    activity(
      "Hay huellas de lodo junto a unos zapatos sucios. ¿Qué puedes deducir?",
      "Es probable que alguien caminara por el lodo.",
      "Sabemos con seguridad qué comió esa persona.",
      "Los zapatos nunca se han usado.",
    ),
    activity(
      "¿Qué puedes deducir por estas pistas?",
      "Es probable que Lina tenga frío.",
      "Lina está nadando.",
      "Lina perdió su tarea.",
      "Lina se puso un suéter, se cubrió con una manta y se frotó las manos.",
    ),
    activity(
      "¿Qué puedes deducir de lo que hace Mateo?",
      "Parece que está buscando algo debajo de la cama.",
      "Ya se quedó dormido.",
      "Está cocinando.",
      "Mateo se arrodilló, encendió una linterna y miró varias veces debajo de la cama.",
    ),
  ),
  word(
    "contexto",
    "contexto",
    ["contextos"],
    "Las palabras y la situación que rodean una palabra y ayudan a entenderla.",
    "En «me senté en el banco», la frase ayuda a entender que banco es un asiento.",
    ["La primera letra de cualquier palabra.", "El precio de un libro."],
    activity(
      "En «El pájaro movió sus alas», ¿qué te ayuda a entender qué son las alas?",
      "El contexto: se habla de un pájaro.",
      "El número de la página.",
      "El color del lápiz.",
    ),
    activity(
      "Por el contexto, ¿qué significa «copa» aquí?",
      "La parte de arriba del árbol, con ramas y hojas.",
      "Un vaso para beber.",
      "Un premio deportivo.",
      "Un pájaro hizo su nido en la copa del árbol, entre las ramas más altas.",
    ),
    activity(
      "Por el contexto, ¿qué significa «planta» aquí?",
      "La parte de abajo del pie.",
      "Una hierba en una maceta.",
      "Un lugar donde se fabrican cosas.",
      "Después de caminar descalza por las piedras, a Rosa le dolía la planta del pie.",
    ),
  ),
  word(
    "evidencia",
    "evidencia",
    ["evidencias"],
    "Un dato o una pista que ayuda a comprobar una idea.",
    "Una frase del cuento puede ser evidencia para apoyar tu respuesta.",
    [
      "Una opinión sin ninguna pista que la apoye.",
      "Algo que siempre debemos inventar.",
    ],
    activity(
      "Dices que el personaje ayudó a su amiga. ¿Qué sería evidencia?",
      "La frase donde le presta su cuaderno.",
      "Que a ti te gustan los amigos.",
      "El color de la portada.",
    ),
    activity(
      "¿Qué evidencia muestra que el grupo cuidó el parque?",
      "Recogieron basura y regaron los árboles.",
      "El parque quedaba cerca.",
      "Era sábado.",
      "El sábado el grupo fue al parque cercano. Recogieron basura y regaron los árboles. Después jugaron juntos.",
    ),
    activity(
      "¿Qué evidencia apoya la idea de que el suelo estaba mojado?",
      "Las suelas dejaron marcas de agua.",
      "La puerta era grande.",
      "El pasillo tenía paredes blancas.",
      "Al entrar por la puerta grande, las suelas de Beto dejaron marcas de agua en el pasillo de paredes blancas.",
    ),
  ),
  word(
    "proposito",
    "propósito",
    ["propósitos"],
    "Lo que alguien quiere lograr al hacer algo.",
    "El propósito de una receta es ayudarte a preparar un alimento.",
    [
      "Lo que sucede sin que nadie lo quiera.",
      "El tamaño de las letras de un texto.",
    ],
    activity(
      "¿Cuál es el propósito de un cartel que invita a una obra de teatro?",
      "Invitar a las personas a ver la obra.",
      "Enseñar a cocinar.",
      "Contar cuántas sillas tiene una casa.",
    ),
    activity(
      "¿Cuál es el propósito de esta nota?",
      "Recordar al grupo que lleve una botella con agua.",
      "Contar un cuento de animales.",
      "Enseñar a construir una mochila.",
      "Nota para el grupo: «Mañana caminaremos al parque. No olviden llevar su botella con agua».",
    ),
    activity(
      "¿Cuál es el propósito de este texto?",
      "Enseñar cómo hacer un separador de libros.",
      "Invitar a una fiesta.",
      "Contar lo que pasó en un partido.",
      "Recorta una tira de cartón. Decórala con tus colores favoritos. Úsala para marcar la página donde dejaste de leer.",
    ),
  ),
];

export function vocabularyQuestion(
  entry: VocabularyWord,
  activityIndex: number,
): Question {
  const a = entry.activities[activityIndex];
  return {
    id: `vocabulary-${entry.id}-${activityIndex}`,
    skill: "VOCABULARY",
    kind: "choice",
    prompt: a.prompt,
    choices: [...a.choices],
    correct: a.choices[0],
    explanation: `${a.choices[0]} ${activityIndex === 0 ? entry.example : `${entry.word}: ${entry.meaning}`}`,
    vocabularyWordId: entry.id,
    vocabularyActivity: activityIndex,
    readingText: a.text,
  };
}
